# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-21 10:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='images/')),
                ('imageName', models.CharField(blank=True, max_length=30)),
                ('imageCaption', models.CharField(blank=True, max_length=30)),
                ('imageComment', models.TextField()),
                ('imageTime', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userBio', models.TextField()),
                ('userPic', models.ImageField(blank=True, default='default.png', upload_to='profileImage/')),
                ('profileTime', models.DateField(auto_now_add=True)),
                ('userF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='profileF',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instasocial.Profile'),
        ),
        migrations.AddField(
            model_name='image',
            name='userF',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
