# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-22 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instasocial', '0003_auto_20191022_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userPic',
            field=models.ImageField(default='default.jpg', upload_to='profileImage/'),
        ),
    ]
